on:
  push:
    branches: [ "master" ]

# Environment variables available to all jobs and steps in this workflow
env:
  CCS: ccr.ccs.tencentyun.com
  NAMESPACE: haicheng

permissions:
  contents: read

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    environment: production
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # Build
    - name: Build Docker image
      run: |
        docker build -t ${CCS}/${NAMESPACE}/frps:${GITHUB_SHA} -f ./dockerfiles/Dockerfile-for-frps .
        docker build -t ${CCS}/${NAMESPACE}/frpc:${GITHUB_SHA} -f ./dockerfiles/Dockerfile-for-frpc .

    - name: Login TKE Registry
      run: |
        docker login -u ${{ secrets.TENCENT_CLOUD_ACCOUNT_ID }} -p '${{ secrets.TKE_REGISTRY_PASSWORD }}' ${CCS}

    # Push the Docker image to TKE Registry
    - name: Publish
      run: |
        docker push ${CCS}/${NAMESPACE}/frps:${GITHUB_SHA}
        docker push ${CCS}/${NAMESPACE}/frpc:${GITHUB_SHA}
